# Generated by Django 2.1.1 on 2018-09-12 01:07

from django.db import migrations
from django.db import models

class Migration(migrations.Migration):

    dependencies = [
        ('mensajes', '0001_initial'),
    ]

    operations = [
            migrations.AlterField('Messege', 'pub_date', models.CharField(max_length=100))
        ]
